const APP_TRACKER = 'APP_TRACKER'
const APP_USER_TOKEN = 'APP_USER_TOKEN'
const APP_USER_INFO = 'APP_USER_INFO'
const APP_STORE = 'APP_STORE'

export const AppActions = {
    APP_TRACKER,
    APP_USER_TOKEN,
    APP_USER_INFO,
    APP_STORE
}